  on: push

  jobs:
    trivy:
      name: Trivy Scan
      runs-on: ubuntu-latest
      steps:
        - name: checkout test
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          run: docker build -t paye-ton-kaya:latest .
        - name: Run Trivy Scan
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: 'paye-ton-kaya:latest'
            format: 'sarif'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'