  on: push

  jobs:
    trivy:
      name: Trivy Scan
      runs-on: ubuntu-latest
      steps:
        - name: checkout test
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          run: docker build -t docker.io/my-organization/my-app:latest
        - name: Run Trivy Scan
          uses: aquasecurity/trivy-action@v0.3.0
          with:
            image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'